baseurl = "/"
languageCode = "en-us"
title = "Automate the Data Exploration Pipeline"
theme = "blackburn"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# enable SEO search
enableRobotsTXT= true
canonifyURLs = true

[permalinks]

post = "/:day/:month/:year/:slug/"

[[menu.main]]
    name= "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name="Projects"
    url="/post"
    weight = 2


[params]
    description = "A Beginner's Guide to Automated Data Analysis with R and Python"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[Social]

twitter = "neuronelsongon"
github = "Nelson-Gon"
stackoverflow = "https://stackoverflow.com/users/10323798/nelsongon"
