baseurl = "/"
languageCode = "en-us"
title = "Nelson Gonzabato"
theme = "blackburn"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]



[[menu.main]]
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Nelson-Gon"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/neuronelsongon"
    weight = 4
[[menu.main]]
    name = "StackOverflow"
    url  = "https://stackoverflow.com/users/10323798/nelsongon"
    weight = 3
[[menu.main]]
    name = "Kaggle"
    url = "https://www.kaggle.com/gonnel"
    weight = 5

[params]
    description = "NelsonGon's personal wesbite"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

