baseurl = "https://nelson-gon.github.io/"
languageCode = "en-us"
title = "Automate the Data Exploration Pipeline"
theme = "blackburn"
author = "Nelsnon Gonzabato"
copyright = "&copy; 2020. All rights reserved."
googleAnalytics = ""
publishDir = "../nelson-gon.github.io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# enable SEO search
enableRobotsTXT= true
canonifyURLs = true
relativeURLs = true
# disable rss
disableKinds = ["RSS"] 

[permalinks]

post = "/:day/:month/:year/:slug/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name= "About"
    url = "/about/"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier="about"

[[menu.main]]
    name="Posts"
    url="/post"
    pre = "<i class='fa fa-list fa-fw'></i>"
    identifier = "psot"
    weight = 3


[params]
    description = "A Beginner's Guide to Automated Data Analysis with R and Python"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[Social]

twitter = "neuronelsongon"
github = "Nelson-Gon"
stackoverflow = "10323798/nelsongon"
kaggle = "gonnel"
